module.exports = [
  {
    id: "001",
    name: "Bulbasaur",
    img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
    type: ["Grass", "Poison"],
    misc: { classification: "seed pokemon" },
    stats: {
      hp: "45",
      attack: "49",
      defense: "49",
      spattack: "65",
      spdefense: "65",
      speed: "45",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "002",
    name: "Ivysaur",
    img: "http://img.pokemondb.net/artwork/ivysaur.jpg",
    type: ["Grass", "Poison"],
    misc: { classification: "seed pokemon" },
    stats: {
      hp: "60",
      attack: "62",
      defense: "63",
      spattack: "80",
      spdefense: "80",
      speed: "60",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "003",
    name: "Venusaur",
    img: "http://img.pokemondb.net/artwork/venusaur.jpg",
    type: ["Grass", "Poison"],
    misc: { classification: "seed pokemon" },
    stats: {
      hp: "80",
      attack: "82",
      defense: "83",
      spattack: "100",
      spdefense: "100",
      speed: "80",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "004",
    name: "Charmander",
    img: "http://img.pokemondb.net/artwork/charmander.jpg",
    type: ["Fire"],
    misc: { classification: "lizard pokemon" },
    stats: {
      hp: "39",
      attack: "52",
      defense: "43",
      spattack: "60",
      spdefense: "50",
      speed: "65",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "1",
      grass: "0.5",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "005",
    name: "Charmeleon",
    img: "http://img.pokemondb.net/artwork/charmeleon.jpg",
    type: ["Fire"],
    misc: { classification: "flame pokemon" },
    stats: {
      hp: "58",
      attack: "64",
      defense: "58",
      spattack: "80",
      spdefense: "65",
      speed: "80",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "1",
      grass: "0.5",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "006",
    name: "Charizard",
    img: "http://img.pokemondb.net/artwork/charizard.jpg",
    type: ["Fire", "Flying"],
    misc: { classification: "flame pokemon" },
    stats: {
      hp: "78",
      attack: "84",
      defense: "78",
      spattack: "109",
      spdefense: "85",
      speed: "100",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "2",
      grass: "0.25",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.25",
      rock: "4",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "007",
    name: "Squirtle",
    img: "http://img.pokemondb.net/artwork/squirtle.jpg",
    type: ["Water"],
    misc: { classification: "tiny turtle pokemon" },
    stats: {
      hp: "44",
      attack: "48",
      defense: "65",
      spattack: "50",
      spdefense: "64",
      speed: "43",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "008",
    name: "Wartortle",
    img: "http://img.pokemondb.net/artwork/wartortle.jpg",
    type: ["Water"],
    misc: { classification: "turtle pokemon" },
    stats: {
      hp: "59",
      attack: "63",
      defense: "80",
      spattack: "65",
      spdefense: "80",
      speed: "58",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "009",
    name: "Blastoise",
    img: "http://img.pokemondb.net/artwork/blastoise.jpg",
    type: ["Water"],
    misc: { classification: "shellfish pokemon" },
    stats: {
      hp: "79",
      attack: "83",
      defense: "100",
      spattack: "85",
      spdefense: "105",
      speed: "78",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "010",
    name: "Caterpie",
    img: "http://img.pokemondb.net/artwork/caterpie.jpg",
    type: ["Bug"],
    misc: { classification: "worm pokemon" },
    stats: {
      hp: "45",
      attack: "30",
      defense: "35",
      spattack: "20",
      spdefense: "20",
      speed: "45",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "0.5",
      flying: "2",
      psychic: "1",
      bug: "1",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "011",
    name: "Metapod",
    img: "http://img.pokemondb.net/artwork/metapod.jpg",
    type: ["Bug"],
    misc: { classification: "cocoon pokemon" },
    stats: {
      hp: "50",
      attack: "20",
      defense: "55",
      spattack: "25",
      spdefense: "25",
      speed: "30",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "0.5",
      flying: "2",
      psychic: "1",
      bug: "1",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "012",
    name: "Butterfree",
    img: "http://img.pokemondb.net/artwork/butterfree.jpg",
    type: ["Bug", "Flying"],
    misc: { classification: "butterfly pokemon" },
    stats: {
      hp: "60",
      attack: "45",
      defense: "50",
      spattack: "80",
      spdefense: "80",
      speed: "70",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "2",
      grass: "0.25",
      ice: "2",
      fight: "0.25",
      poison: "1",
      ground: "0",
      flying: "2",
      psychic: "1",
      bug: "0.5",
      rock: "4",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "013",
    name: "Weedle",
    img: "http://img.pokemondb.net/artwork/weedle.jpg",
    type: ["Bug", "Poison"],
    misc: { classification: "hairy pokemon" },
    stats: {
      hp: "40",
      attack: "35",
      defense: "30",
      spattack: "20",
      spdefense: "20",
      speed: "50",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "1",
      grass: "0.25",
      ice: "1",
      fight: "0.25",
      poison: "0.5",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "014",
    name: "Kakuna",
    img: "http://img.pokemondb.net/artwork/kakuna.jpg",
    type: ["Bug", "Poison"],
    misc: { classification: "cocoon pokemon" },
    stats: {
      hp: "45",
      attack: "25",
      defense: "50",
      spattack: "25",
      spdefense: "25",
      speed: "35",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "1",
      grass: "0.25",
      ice: "1",
      fight: "0.25",
      poison: "0.5",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "015",
    name: "Beedrill",
    img: "http://img.pokemondb.net/artwork/beedrill.jpg",
    type: ["Bug", "Poison"],
    misc: { classification: "poison bee pokemon" },
    stats: {
      hp: "65",
      attack: "80",
      defense: "40",
      spattack: "45",
      spdefense: "80",
      speed: "75",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "1",
      grass: "0.25",
      ice: "1",
      fight: "0.25",
      poison: "0.5",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "016",
    name: "Pidgey",
    img: "http://img.pokemondb.net/artwork/pidgey.jpg",
    type: ["Normal", "Flying"],
    misc: { classification: "tiny bird pokemon" },
    stats: {
      hp: "40",
      attack: "45",
      defense: "40",
      spattack: "35",
      spdefense: "35",
      speed: "56",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "2",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "017",
    name: "Pidgeotto",
    img: "http://img.pokemondb.net/artwork/pidgeotto.jpg",
    type: ["Normal", "Flying"],
    misc: { classification: "bird pokemon" },
    stats: {
      hp: "63",
      attack: "60",
      defense: "55",
      spattack: "50",
      spdefense: "50",
      speed: "71",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "2",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "018",
    name: "Pidgeot",
    img: "http://img.pokemondb.net/artwork/pidgeot.jpg",
    type: ["Normal", "Flying"],
    misc: { classification: "bird pokemon" },
    stats: {
      hp: "83",
      attack: "80",
      defense: "75",
      spattack: "70",
      spdefense: "70",
      speed: "91",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "2",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "019",
    name: "Rattata",
    img: "http://img.pokemondb.net/artwork/rattata.jpg",
    type: ["Normal"],
    misc: { classification: "mouse pokemon" },
    stats: {
      hp: "30",
      attack: "56",
      defense: "35",
      spattack: "25",
      spdefense: "35",
      speed: "72",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "020",
    name: "Raticate",
    img: "http://img.pokemondb.net/artwork/raticate.jpg",
    type: ["Normal"],
    misc: { classification: "mouse pokemon" },
    stats: {
      hp: "55",
      attack: "81",
      defense: "60",
      spattack: "50",
      spdefense: "70",
      speed: "97",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "021",
    name: "Spearow",
    img: "http://img.pokemondb.net/artwork/spearow.jpg",
    type: ["Normal", "Flying"],
    misc: { classification: "tiny bird pokemon" },
    stats: {
      hp: "40",
      attack: "60",
      defense: "30",
      spattack: "31",
      spdefense: "31",
      speed: "70",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "2",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "022",
    name: "Fearow",
    img: "http://img.pokemondb.net/artwork/fearow.jpg",
    type: ["Normal", "Flying"],
    misc: { classification: "beak pokemon" },
    stats: {
      hp: "65",
      attack: "90",
      defense: "65",
      spattack: "61",
      spdefense: "61",
      speed: "100",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "2",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "023",
    name: "Ekans",
    img: "http://img.pokemondb.net/artwork/ekans.jpg",
    type: ["Poison"],
    misc: { classification: "snake pokemon" },
    stats: {
      hp: "35",
      attack: "60",
      defense: "44",
      spattack: "40",
      spdefense: "54",
      speed: "55",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "024",
    name: "Arbok",
    img: "http://img.pokemondb.net/artwork/arbok.jpg",
    type: ["Poison"],
    misc: { classification: "cobra pokemon" },
    stats: {
      hp: "60",
      attack: "85",
      defense: "69",
      spattack: "65",
      spdefense: "79",
      speed: "80",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "025",
    name: "Pikachu",
    img: "http://img.pokemondb.net/artwork/pikachu.jpg",
    type: ["Electric"],
    misc: { classification: "mouse pokemon" },
    stats: {
      hp: "35",
      attack: "55",
      defense: "30",
      spattack: "50",
      spdefense: "40",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "0.5",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "026",
    name: "Raichu",
    img: "http://img.pokemondb.net/artwork/raichu.jpg",
    type: ["Electric"],
    misc: { classification: "mouse pokemon" },
    stats: {
      hp: "60",
      attack: "90",
      defense: "55",
      spattack: "90",
      spdefense: "80",
      speed: "100",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "0.5",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "027",
    name: "Sandshrew",
    img: "http://img.pokemondb.net/artwork/sandshrew.jpg",
    type: ["Ground"],
    misc: { classification: "mouse pokemon" },
    stats: {
      hp: "50",
      attack: "75",
      defense: "85",
      spattack: "20",
      spdefense: "30",
      speed: "40",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "2",
      electric: "0",
      grass: "2",
      ice: "2",
      fight: "1",
      poison: "0.5",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "028",
    name: "Sandslash",
    img: "http://img.pokemondb.net/artwork/sandslash.jpg",
    type: ["Ground"],
    misc: { classification: "mouse pokemon" },
    stats: {
      hp: "75",
      attack: "100",
      defense: "110",
      spattack: "45",
      spdefense: "55",
      speed: "65",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "2",
      electric: "0",
      grass: "2",
      ice: "2",
      fight: "1",
      poison: "0.5",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "029",
    name: "Nidoran?",
    img: "https://img.pokemondb.net/artwork/nidoran-f.jpg",
    type: ["Poison"],
    misc: { classification: "poison pin pokemon" },
    stats: {
      hp: "55",
      attack: "47",
      defense: "52",
      spattack: "40",
      spdefense: "40",
      speed: "41",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "030",
    name: "Nidorina",
    img: "http://img.pokemondb.net/artwork/nidorina.jpg",
    type: ["Poison"],
    misc: { classification: "poison pin pokemon" },
    stats: {
      hp: "70",
      attack: "62",
      defense: "67",
      spattack: "55",
      spdefense: "55",
      speed: "56",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "031",
    name: "Nidoqueen",
    img: "http://img.pokemondb.net/artwork/nidoqueen.jpg",
    type: ["Poison", "Ground"],
    misc: { classification: "drill pokemon" },
    stats: {
      hp: "90",
      attack: "82",
      defense: "87",
      spattack: "75",
      spdefense: "85",
      speed: "76",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "2",
      electric: "0",
      grass: "1",
      ice: "2",
      fight: "0.5",
      poison: "0.25",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "032",
    name: "Nidoran?",
    img: "https://img.pokemondb.net/artwork/nidoran-m.jpg",
    type: ["Poison"],
    misc: { classification: "poison pin pokemon" },
    stats: {
      hp: "46",
      attack: "57",
      defense: "40",
      spattack: "40",
      spdefense: "40",
      speed: "50",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "033",
    name: "Nidorino",
    img: "http://img.pokemondb.net/artwork/nidorino.jpg",
    type: ["Poison"],
    misc: { classification: "poison pin pokemon" },
    stats: {
      hp: "61",
      attack: "72",
      defense: "57",
      spattack: "55",
      spdefense: "55",
      speed: "65",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "034",
    name: "Nidoking",
    img: "http://img.pokemondb.net/artwork/nidoking.jpg",
    type: ["Poison", "Ground"],
    misc: { classification: "drill pokemon" },
    stats: {
      hp: "81",
      attack: "92",
      defense: "77",
      spattack: "85",
      spdefense: "75",
      speed: "85",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "2",
      electric: "0",
      grass: "1",
      ice: "2",
      fight: "0.5",
      poison: "0.25",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "035",
    name: "Clefairy",
    img: "http://img.pokemondb.net/artwork/clefairy.jpg",
    type: ["Normal"],
    misc: { classification: "fairy pokemon" },
    stats: {
      hp: "70",
      attack: "45",
      defense: "48",
      spattack: "60",
      spdefense: "65",
      speed: "35",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "036",
    name: "Clefable",
    img: "http://img.pokemondb.net/artwork/clefable.jpg",
    type: ["Normal"],
    misc: { classification: "fairy pokemon" },
    stats: {
      hp: "95",
      attack: "70",
      defense: "73",
      spattack: "85",
      spdefense: "90",
      speed: "60",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "037",
    name: "Vulpix",
    img: "http://img.pokemondb.net/artwork/vulpix.jpg",
    type: ["Fire"],
    misc: { classification: "fox pokemon" },
    stats: {
      hp: "38",
      attack: "41",
      defense: "40",
      spattack: "50",
      spdefense: "65",
      speed: "65",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "1",
      grass: "0.5",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "038",
    name: "Ninetales",
    img: "http://img.pokemondb.net/artwork/ninetales.jpg",
    type: ["Fire"],
    misc: { classification: "fox pokemon" },
    stats: {
      hp: "73",
      attack: "76",
      defense: "75",
      spattack: "81",
      spdefense: "100",
      speed: "100",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "1",
      grass: "0.5",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "039",
    name: "Jigglypuff",
    img: "http://img.pokemondb.net/artwork/jigglypuff.jpg",
    type: ["Normal"],
    misc: { classification: "balloon pokemon" },
    stats: {
      hp: "115",
      attack: "45",
      defense: "20",
      spattack: "45",
      spdefense: "25",
      speed: "20",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "040",
    name: "Wigglytuff",
    img: "http://img.pokemondb.net/artwork/wigglytuff.jpg",
    type: ["Normal"],
    misc: { classification: "balloon pokemon" },
    stats: {
      hp: "140",
      attack: "70",
      defense: "45",
      spattack: "75",
      spdefense: "50",
      speed: "45",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "041",
    name: "Zubat",
    img: "http://img.pokemondb.net/artwork/zubat.jpg",
    type: ["Poison", "Flying"],
    misc: { classification: "bat pokemon" },
    stats: {
      hp: "40",
      attack: "45",
      defense: "35",
      spattack: "30",
      spdefense: "40",
      speed: "55",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "2",
      grass: "0.25",
      ice: "2",
      fight: "0.25",
      poison: "0.5",
      ground: "0",
      flying: "1",
      psychic: "2",
      bug: "0.25",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "042",
    name: "Golbat",
    img: "http://img.pokemondb.net/artwork/golbat.jpg",
    type: ["Poison", "Flying"],
    misc: { classification: "bat pokemon" },
    stats: {
      hp: "75",
      attack: "80",
      defense: "70",
      spattack: "65",
      spdefense: "75",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "2",
      grass: "0.25",
      ice: "2",
      fight: "0.25",
      poison: "0.5",
      ground: "0",
      flying: "1",
      psychic: "2",
      bug: "0.25",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "043",
    name: "Oddish",
    img: "http://img.pokemondb.net/artwork/oddish.jpg",
    type: ["Grass", "Poison"],
    misc: { classification: "weed pokemon" },
    stats: {
      hp: "45",
      attack: "50",
      defense: "55",
      spattack: "75",
      spdefense: "65",
      speed: "30",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "044",
    name: "Gloom",
    img: "http://img.pokemondb.net/artwork/gloom.jpg",
    type: ["Grass", "Poison"],
    misc: { classification: "weed pokemon" },
    stats: {
      hp: "60",
      attack: "65",
      defense: "70",
      spattack: "85",
      spdefense: "75",
      speed: "40",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "045",
    name: "Vileplume",
    img: "http://img.pokemondb.net/artwork/vileplume.jpg",
    type: ["Grass", "Poison"],
    misc: { classification: "flower pokemon" },
    stats: {
      hp: "75",
      attack: "80",
      defense: "85",
      spattack: "100",
      spdefense: "90",
      speed: "50",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "046",
    name: "Paras",
    img: "http://img.pokemondb.net/artwork/paras.jpg",
    type: ["Bug", "Grass"],
    misc: { classification: "mushroom pokemon" },
    stats: {
      hp: "35",
      attack: "70",
      defense: "55",
      spattack: "45",
      spdefense: "55",
      speed: "25",
    },
    damages: {
      normal: "1",
      fire: "4",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "2",
      ground: "0.25",
      flying: "4",
      psychic: "1",
      bug: "2",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "047",
    name: "Parasect",
    img: "http://img.pokemondb.net/artwork/parasect.jpg",
    type: ["Bug", "Grass"],
    misc: { classification: "mushroom pokemon" },
    stats: {
      hp: "60",
      attack: "95",
      defense: "80",
      spattack: "60",
      spdefense: "80",
      speed: "30",
    },
    damages: {
      normal: "1",
      fire: "4",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "2",
      ground: "0.25",
      flying: "4",
      psychic: "1",
      bug: "2",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "048",
    name: "Venonat",
    img: "http://img.pokemondb.net/artwork/venonat.jpg",
    type: ["Bug", "Poison"],
    misc: { classification: "insect pokemon" },
    stats: {
      hp: "60",
      attack: "55",
      defense: "50",
      spattack: "40",
      spdefense: "55",
      speed: "45",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "1",
      grass: "0.25",
      ice: "1",
      fight: "0.25",
      poison: "0.5",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "049",
    name: "Venomoth",
    img: "http://img.pokemondb.net/artwork/venomoth.jpg",
    type: ["Bug", "Poison"],
    misc: { classification: "poison moth pokemon" },
    stats: {
      hp: "70",
      attack: "65",
      defense: "60",
      spattack: "90",
      spdefense: "75",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "1",
      grass: "0.25",
      ice: "1",
      fight: "0.25",
      poison: "0.5",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "050",
    name: "Diglett",
    img: "http://img.pokemondb.net/artwork/diglett.jpg",
    type: ["Ground"],
    misc: { classification: "mole pokemon" },
    stats: {
      hp: "10",
      attack: "55",
      defense: "25",
      spattack: "35",
      spdefense: "45",
      speed: "95",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "2",
      electric: "0",
      grass: "2",
      ice: "2",
      fight: "1",
      poison: "0.5",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "051",
    name: "Dugtrio",
    img: "http://img.pokemondb.net/artwork/dugtrio.jpg",
    type: ["Ground"],
    misc: { classification: "mole pokemon" },
    stats: {
      hp: "35",
      attack: "80",
      defense: "50",
      spattack: "50",
      spdefense: "70",
      speed: "120",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "2",
      electric: "0",
      grass: "2",
      ice: "2",
      fight: "1",
      poison: "0.5",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "052",
    name: "Meowth",
    img: "http://img.pokemondb.net/artwork/meowth.jpg",
    type: ["Normal"],
    misc: { classification: "scratch cat pokemon" },
    stats: {
      hp: "40",
      attack: "45",
      defense: "35",
      spattack: "40",
      spdefense: "40",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "053",
    name: "Persian",
    img: "http://img.pokemondb.net/artwork/persian.jpg",
    type: ["Normal"],
    misc: { classification: "classy cat pokemon" },
    stats: {
      hp: "65",
      attack: "70",
      defense: "60",
      spattack: "65",
      spdefense: "65",
      speed: "115",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "054",
    name: "Psyduck",
    img: "http://img.pokemondb.net/artwork/psyduck.jpg",
    type: ["Water"],
    misc: { classification: "duck pokemon" },
    stats: {
      hp: "50",
      attack: "52",
      defense: "48",
      spattack: "65",
      spdefense: "50",
      speed: "55",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "055",
    name: "Golduck",
    img: "http://img.pokemondb.net/artwork/golduck.jpg",
    type: ["Water"],
    misc: { classification: "duck pokemon" },
    stats: {
      hp: "80",
      attack: "82",
      defense: "78",
      spattack: "95",
      spdefense: "80",
      speed: "85",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "056",
    name: "Mankey",
    img: "http://img.pokemondb.net/artwork/mankey.jpg",
    type: ["Fighting"],
    misc: { classification: "pig monkey pokemon" },
    stats: {
      hp: "40",
      attack: "80",
      defense: "35",
      spattack: "35",
      spdefense: "45",
      speed: "70",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "0.5",
      steel: "1",
    },
  },
  {
    id: "057",
    name: "Primeape",
    img: "http://img.pokemondb.net/artwork/primeape.jpg",
    type: ["Fighting"],
    misc: { classification: "pig monkey pokemon" },
    stats: {
      hp: "65",
      attack: "105",
      defense: "60",
      spattack: "60",
      spdefense: "70",
      speed: "95",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "0.5",
      steel: "1",
    },
  },
  {
    id: "058",
    name: "Growlithe",
    img: "http://img.pokemondb.net/artwork/growlithe.jpg",
    type: ["Fire"],
    misc: { classification: "puppy pokemon" },
    stats: {
      hp: "55",
      attack: "70",
      defense: "45",
      spattack: "70",
      spdefense: "50",
      speed: "60",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "1",
      grass: "0.5",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "059",
    name: "Arcanine",
    img: "http://img.pokemondb.net/artwork/arcanine.jpg",
    type: ["Fire"],
    misc: { classification: "legendary pokemon" },
    stats: {
      hp: "90",
      attack: "110",
      defense: "80",
      spattack: "100",
      spdefense: "80",
      speed: "95",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "1",
      grass: "0.5",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "060",
    name: "Poliwag",
    img: "http://img.pokemondb.net/artwork/poliwag.jpg",
    type: ["Water"],
    misc: { classification: "tadpole pokemon" },
    stats: {
      hp: "40",
      attack: "50",
      defense: "40",
      spattack: "40",
      spdefense: "40",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "061",
    name: "Poliwhirl",
    img: "http://img.pokemondb.net/artwork/poliwhirl.jpg",
    type: ["Water"],
    misc: { classification: "tadpole pokemon" },
    stats: {
      hp: "65",
      attack: "65",
      defense: "65",
      spattack: "50",
      spdefense: "50",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "062",
    name: "Poliwrath",
    img: "http://img.pokemondb.net/artwork/poliwrath.jpg",
    type: ["Water", "Fighting"],
    misc: { classification: "tadpole pokemon" },
    stats: {
      hp: "90",
      attack: "85",
      defense: "95",
      spattack: "70",
      spdefense: "90",
      speed: "70",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "0.5",
      steel: "0.5",
    },
  },
  {
    id: "063",
    name: "Abra",
    img: "http://img.pokemondb.net/artwork/abra.jpg",
    type: ["Psychic"],
    misc: { classification: "psi pokemon" },
    stats: {
      hp: "25",
      attack: "20",
      defense: "15",
      spattack: "105",
      spdefense: "55",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "064",
    name: "Kadabra",
    img: "http://img.pokemondb.net/artwork/kadabra.jpg",
    type: ["Psychic"],
    misc: { classification: "psi pokemon" },
    stats: {
      hp: "40",
      attack: "35",
      defense: "30",
      spattack: "120",
      spdefense: "70",
      speed: "105",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "065",
    name: "Alakazam",
    img: "http://img.pokemondb.net/artwork/alakazam.jpg",
    type: ["Psychic"],
    misc: { classification: "psi pokemon" },
    stats: {
      hp: "55",
      attack: "50",
      defense: "45",
      spattack: "135",
      spdefense: "85",
      speed: "120",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "066",
    name: "Machop",
    img: "http://img.pokemondb.net/artwork/machop.jpg",
    type: ["Fighting"],
    misc: { classification: "superpower pokemon" },
    stats: {
      hp: "70",
      attack: "80",
      defense: "50",
      spattack: "35",
      spdefense: "35",
      speed: "35",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "0.5",
      steel: "1",
    },
  },
  {
    id: "067",
    name: "Machoke",
    img: "http://img.pokemondb.net/artwork/machoke.jpg",
    type: ["Fighting"],
    misc: { classification: "superpower pokemon" },
    stats: {
      hp: "80",
      attack: "100",
      defense: "70",
      spattack: "50",
      spdefense: "60",
      speed: "45",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "0.5",
      steel: "1",
    },
  },
  {
    id: "068",
    name: "Machamp",
    img: "http://img.pokemondb.net/artwork/machamp.jpg",
    type: ["Fighting"],
    misc: { classification: "superpower pokemon" },
    stats: {
      hp: "90",
      attack: "130",
      defense: "80",
      spattack: "65",
      spdefense: "85",
      speed: "55",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "0.5",
      steel: "1",
    },
  },
  {
    id: "069",
    name: "Bellsprout",
    img: "http://img.pokemondb.net/artwork/bellsprout.jpg",
    type: ["Grass", "Poison"],
    misc: { classification: "flower pokemon" },
    stats: {
      hp: "50",
      attack: "75",
      defense: "35",
      spattack: "70",
      spdefense: "30",
      speed: "40",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "070",
    name: "Weepinbell",
    img: "http://img.pokemondb.net/artwork/weepinbell.jpg",
    type: ["Grass", "Poison"],
    misc: { classification: "flycatcher pokemon" },
    stats: {
      hp: "65",
      attack: "90",
      defense: "50",
      spattack: "85",
      spdefense: "45",
      speed: "55",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "071",
    name: "Victreebel",
    img: "http://img.pokemondb.net/artwork/victreebel.jpg",
    type: ["Grass", "Poison"],
    misc: { classification: "flycatcher pokemon" },
    stats: {
      hp: "80",
      attack: "105",
      defense: "65",
      spattack: "100",
      spdefense: "60",
      speed: "70",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.25",
      ice: "2",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "072",
    name: "Tentacool",
    img: "http://img.pokemondb.net/artwork/tentacool.jpg",
    type: ["Water", "Poison"],
    misc: { classification: "jellyfish pokemon" },
    stats: {
      hp: "40",
      attack: "40",
      defense: "35",
      spattack: "50",
      spdefense: "100",
      speed: "70",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "1",
      ice: "0.5",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "073",
    name: "Tentacruel",
    img: "http://img.pokemondb.net/artwork/tentacruel.jpg",
    type: ["Water", "Poison"],
    misc: { classification: "jellyfish pokemon" },
    stats: {
      hp: "80",
      attack: "70",
      defense: "65",
      spattack: "80",
      spdefense: "120",
      speed: "100",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "1",
      ice: "0.5",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "074",
    name: "Geodude",
    img: "http://img.pokemondb.net/artwork/geodude.jpg",
    type: ["Rock", "Ground"],
    misc: { classification: "rock pokemon" },
    stats: {
      hp: "40",
      attack: "80",
      defense: "100",
      spattack: "30",
      spdefense: "30",
      speed: "20",
    },
    damages: {
      normal: "0.5",
      fire: "0.5",
      water: "4",
      electric: "0",
      grass: "4",
      ice: "2",
      fight: "2",
      poison: "0.25",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "2",
    },
  },
  {
    id: "075",
    name: "Graveler",
    img: "http://img.pokemondb.net/artwork/graveler.jpg",
    type: ["Rock", "Ground"],
    misc: { classification: "rock pokemon" },
    stats: {
      hp: "55",
      attack: "95",
      defense: "115",
      spattack: "45",
      spdefense: "45",
      speed: "35",
    },
    damages: {
      normal: "0.5",
      fire: "0.5",
      water: "4",
      electric: "0",
      grass: "4",
      ice: "2",
      fight: "2",
      poison: "0.25",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "2",
    },
  },
  {
    id: "076",
    name: "Golem",
    img: "http://img.pokemondb.net/artwork/golem.jpg",
    type: ["Rock", "Ground"],
    misc: { classification: "megaton pokemon" },
    stats: {
      hp: "80",
      attack: "110",
      defense: "130",
      spattack: "55",
      spdefense: "65",
      speed: "45",
    },
    damages: {
      normal: "0.5",
      fire: "0.5",
      water: "4",
      electric: "0",
      grass: "4",
      ice: "2",
      fight: "2",
      poison: "0.25",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "2",
    },
  },
  {
    id: "077",
    name: "Ponyta",
    img: "http://img.pokemondb.net/artwork/ponyta.jpg",
    type: ["Fire"],
    misc: { classification: "fire horse pokemon" },
    stats: {
      hp: "50",
      attack: "85",
      defense: "55",
      spattack: "65",
      spdefense: "65",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "1",
      grass: "0.5",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "078",
    name: "Rapidash",
    img: "http://img.pokemondb.net/artwork/rapidash.jpg",
    type: ["Fire"],
    misc: { classification: "fire horse pokemon" },
    stats: {
      hp: "65",
      attack: "100",
      defense: "70",
      spattack: "80",
      spdefense: "80",
      speed: "105",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "1",
      grass: "0.5",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "079",
    name: "Slowpoke",
    img: "http://img.pokemondb.net/artwork/slowpoke.jpg",
    type: ["Water", "Psychic"],
    misc: { classification: "dopey pokemon" },
    stats: {
      hp: "90",
      attack: "65",
      defense: "65",
      spattack: "40",
      spdefense: "40",
      speed: "15",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "0.5",
    },
  },
  {
    id: "080",
    name: "Slowbro",
    img: "http://img.pokemondb.net/artwork/slowbro.jpg",
    type: ["Water", "Psychic"],
    misc: { classification: "hermit crab pokemon" },
    stats: {
      hp: "95",
      attack: "75",
      defense: "110",
      spattack: "100",
      spdefense: "80",
      speed: "30",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "0.5",
    },
  },
  {
    id: "081",
    name: "Magnemite",
    img: "http://img.pokemondb.net/artwork/magnemite.jpg",
    type: ["Electric", "Steel"],
    misc: { classification: "magnet pokemon" },
    stats: {
      hp: "25",
      attack: "35",
      defense: "70",
      spattack: "95",
      spdefense: "55",
      speed: "45",
    },
    damages: {
      normal: "0.5",
      fire: "2",
      water: "1",
      electric: "0.5",
      grass: "0.5",
      ice: "0.5",
      fight: "2",
      poison: "0",
      ground: "4",
      flying: "0.25",
      psychic: "0.5",
      bug: "0.5",
      rock: "0.5",
      ghost: "0.5",
      dragon: "0.5",
      dark: "0.5",
      steel: "0.25",
    },
  },
  {
    id: "082",
    name: "Magneton",
    img: "http://img.pokemondb.net/artwork/magneton.jpg",
    type: ["Electric", "Steel"],
    misc: { classification: "magnet pokemon" },
    stats: {
      hp: "50",
      attack: "60",
      defense: "95",
      spattack: "120",
      spdefense: "70",
      speed: "70",
    },
    damages: {
      normal: "0.5",
      fire: "2",
      water: "1",
      electric: "0.5",
      grass: "0.5",
      ice: "0.5",
      fight: "2",
      poison: "0",
      ground: "4",
      flying: "0.25",
      psychic: "0.5",
      bug: "0.5",
      rock: "0.5",
      ghost: "0.5",
      dragon: "0.5",
      dark: "0.5",
      steel: "0.25",
    },
  },
  {
    id: "083",
    name: "Farfetch'd",
    img: "http://img.pokemondb.net/artwork/farfetchd.jpg",
    type: ["Normal", "Flying"],
    misc: { classification: "wild duck pokemon" },
    stats: {
      hp: "52",
      attack: "65",
      defense: "55",
      spattack: "58",
      spdefense: "62",
      speed: "60",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "2",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "084",
    name: "Doduo",
    img: "http://img.pokemondb.net/artwork/doduo.jpg",
    type: ["Normal", "Flying"],
    misc: { classification: "twin bird pokemon" },
    stats: {
      hp: "35",
      attack: "85",
      defense: "45",
      spattack: "35",
      spdefense: "35",
      speed: "75",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "2",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "085",
    name: "Dodrio",
    img: "http://img.pokemondb.net/artwork/dodrio.jpg",
    type: ["Normal", "Flying"],
    misc: { classification: "triple bird pokemon" },
    stats: {
      hp: "60",
      attack: "110",
      defense: "70",
      spattack: "60",
      spdefense: "60",
      speed: "100",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "2",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "086",
    name: "Seel",
    img: "http://img.pokemondb.net/artwork/seel.jpg",
    type: ["Water"],
    misc: { classification: "sea lion pokemon" },
    stats: {
      hp: "65",
      attack: "45",
      defense: "55",
      spattack: "45",
      spdefense: "70",
      speed: "45",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "087",
    name: "Dewgong",
    img: "http://img.pokemondb.net/artwork/dewgong.jpg",
    type: ["Water", "Ice"],
    misc: { classification: "sea lion pokemon" },
    stats: {
      hp: "90",
      attack: "70",
      defense: "80",
      spattack: "70",
      spdefense: "95",
      speed: "70",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.25",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "088",
    name: "Grimer",
    img: "http://img.pokemondb.net/artwork/grimer.jpg",
    type: ["Poison"],
    misc: { classification: "sludge pokemon" },
    stats: {
      hp: "80",
      attack: "80",
      defense: "50",
      spattack: "40",
      spdefense: "50",
      speed: "25",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "089",
    name: "Muk",
    img: "http://img.pokemondb.net/artwork/muk.jpg",
    type: ["Poison"],
    misc: { classification: "sludge pokemon" },
    stats: {
      hp: "105",
      attack: "105",
      defense: "75",
      spattack: "65",
      spdefense: "100",
      speed: "50",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "090",
    name: "Shellder",
    img: "http://img.pokemondb.net/artwork/shellder.jpg",
    type: ["Water"],
    misc: { classification: "bivalve pokemon" },
    stats: {
      hp: "30",
      attack: "65",
      defense: "100",
      spattack: "45",
      spdefense: "25",
      speed: "40",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "091",
    name: "Cloyster",
    img: "http://img.pokemondb.net/artwork/cloyster.jpg",
    type: ["Water", "Ice"],
    misc: { classification: "bivalve pokemon" },
    stats: {
      hp: "50",
      attack: "95",
      defense: "180",
      spattack: "85",
      spdefense: "45",
      speed: "70",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.25",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "092",
    name: "Gastly",
    img: "http://img.pokemondb.net/artwork/gastly.jpg",
    type: ["Ghost", "Poison"],
    misc: { classification: "gas pokemon" },
    stats: {
      hp: "30",
      attack: "35",
      defense: "30",
      spattack: "100",
      spdefense: "35",
      speed: "80",
    },
    damages: {
      normal: "0",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0",
      poison: "0.25",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.25",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "093",
    name: "Haunter",
    img: "http://img.pokemondb.net/artwork/haunter.jpg",
    type: ["Ghost", "Poison"],
    misc: { classification: "gas pokemon" },
    stats: {
      hp: "45",
      attack: "50",
      defense: "45",
      spattack: "115",
      spdefense: "55",
      speed: "95",
    },
    damages: {
      normal: "0",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0",
      poison: "0.25",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.25",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "094",
    name: "Gengar",
    img: "http://img.pokemondb.net/artwork/gengar.jpg",
    type: ["Ghost", "Poison"],
    misc: { classification: "shadow pokemon" },
    stats: {
      hp: "60",
      attack: "65",
      defense: "60",
      spattack: "130",
      spdefense: "75",
      speed: "110",
    },
    damages: {
      normal: "0",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0",
      poison: "0.25",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.25",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "095",
    name: "Onix",
    img: "http://img.pokemondb.net/artwork/onix.jpg",
    type: ["Rock", "Ground"],
    misc: { classification: "rock snake pokemon" },
    stats: {
      hp: "35",
      attack: "45",
      defense: "160",
      spattack: "30",
      spdefense: "45",
      speed: "70",
    },
    damages: {
      normal: "0.5",
      fire: "0.5",
      water: "4",
      electric: "0",
      grass: "4",
      ice: "2",
      fight: "2",
      poison: "0.25",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "2",
    },
  },
  {
    id: "096",
    name: "Drowzee",
    img: "http://img.pokemondb.net/artwork/drowzee.jpg",
    type: ["Psychic"],
    misc: { classification: "hypnosis pokemon" },
    stats: {
      hp: "60",
      attack: "48",
      defense: "45",
      spattack: "43",
      spdefense: "90",
      speed: "42",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "097",
    name: "Hypno",
    img: "http://img.pokemondb.net/artwork/hypno.jpg",
    type: ["Psychic"],
    misc: { classification: "hypnosis pokemon" },
    stats: {
      hp: "85",
      attack: "73",
      defense: "70",
      spattack: "73",
      spdefense: "115",
      speed: "67",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "098",
    name: "Krabby",
    img: "http://img.pokemondb.net/artwork/krabby.jpg",
    type: ["Water"],
    misc: { classification: "river crab pokemon" },
    stats: {
      hp: "30",
      attack: "105",
      defense: "90",
      spattack: "25",
      spdefense: "25",
      speed: "50",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "099",
    name: "Kingler",
    img: "http://img.pokemondb.net/artwork/kingler.jpg",
    type: ["Water"],
    misc: { classification: "pincer pokemon" },
    stats: {
      hp: "55",
      attack: "130",
      defense: "115",
      spattack: "50",
      spdefense: "50",
      speed: "75",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "100",
    name: "Voltorb",
    img: "http://img.pokemondb.net/artwork/voltorb.jpg",
    type: ["Electric"],
    misc: { classification: "ball pokemon" },
    stats: {
      hp: "40",
      attack: "30",
      defense: "50",
      spattack: "55",
      spdefense: "55",
      speed: "100",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "0.5",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "101",
    name: "Electrode",
    img: "http://img.pokemondb.net/artwork/electrode.jpg",
    type: ["Electric"],
    misc: { classification: "ball pokemon" },
    stats: {
      hp: "60",
      attack: "50",
      defense: "70",
      spattack: "80",
      spdefense: "80",
      speed: "140",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "0.5",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "102",
    name: "Exeggcute",
    img: "http://img.pokemondb.net/artwork/exeggcute.jpg",
    type: ["Grass", "Psychic"],
    misc: { classification: "egg pokemon" },
    stats: {
      hp: "60",
      attack: "40",
      defense: "80",
      spattack: "60",
      spdefense: "45",
      speed: "40",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.5",
      ice: "2",
      fight: "0.5",
      poison: "2",
      ground: "0.5",
      flying: "2",
      psychic: "0.5",
      bug: "4",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "103",
    name: "Exeggutor",
    img: "http://img.pokemondb.net/artwork/exeggutor.jpg",
    type: ["Grass", "Psychic"],
    misc: { classification: "coconut pokemon" },
    stats: {
      hp: "95",
      attack: "95",
      defense: "85",
      spattack: "125",
      spdefense: "65",
      speed: "55",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.5",
      ice: "2",
      fight: "0.5",
      poison: "2",
      ground: "0.5",
      flying: "2",
      psychic: "0.5",
      bug: "4",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "104",
    name: "Cubone",
    img: "http://img.pokemondb.net/artwork/cubone.jpg",
    type: ["Ground"],
    misc: { classification: "lonely pokemon" },
    stats: {
      hp: "50",
      attack: "50",
      defense: "95",
      spattack: "40",
      spdefense: "50",
      speed: "35",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "2",
      electric: "0",
      grass: "2",
      ice: "2",
      fight: "1",
      poison: "0.5",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "105",
    name: "Marowak",
    img: "http://img.pokemondb.net/artwork/marowak.jpg",
    type: ["Ground"],
    misc: { classification: "bone keeper pokemon" },
    stats: {
      hp: "60",
      attack: "80",
      defense: "110",
      spattack: "50",
      spdefense: "80",
      speed: "45",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "2",
      electric: "0",
      grass: "2",
      ice: "2",
      fight: "1",
      poison: "0.5",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "106",
    name: "Hitmonlee",
    img: "http://img.pokemondb.net/artwork/hitmonlee.jpg",
    type: ["Fighting"],
    misc: { classification: "kicking pokemon" },
    stats: {
      hp: "50",
      attack: "120",
      defense: "53",
      spattack: "35",
      spdefense: "110",
      speed: "87",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "0.5",
      steel: "1",
    },
  },
  {
    id: "107",
    name: "Hitmonchan",
    img: "http://img.pokemondb.net/artwork/hitmonchan.jpg",
    type: ["Fighting"],
    misc: { classification: "punching pokemon" },
    stats: {
      hp: "50",
      attack: "105",
      defense: "79",
      spattack: "35",
      spdefense: "110",
      speed: "76",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "2",
      psychic: "2",
      bug: "0.5",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "0.5",
      steel: "1",
    },
  },
  {
    id: "108",
    name: "Lickitung",
    img: "http://img.pokemondb.net/artwork/lickitung.jpg",
    type: ["Normal"],
    misc: { classification: "licking pokemon" },
    stats: {
      hp: "90",
      attack: "55",
      defense: "75",
      spattack: "60",
      spdefense: "75",
      speed: "30",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "109",
    name: "Koffing",
    img: "http://img.pokemondb.net/artwork/koffing.jpg",
    type: ["Poison"],
    misc: { classification: "poison gas pokemon" },
    stats: {
      hp: "40",
      attack: "65",
      defense: "95",
      spattack: "60",
      spdefense: "45",
      speed: "35",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "110",
    name: "Weezing",
    img: "http://img.pokemondb.net/artwork/weezing.jpg",
    type: ["Poison"],
    misc: { classification: "poison gas pokemon" },
    stats: {
      hp: "65",
      attack: "90",
      defense: "120",
      spattack: "85",
      spdefense: "70",
      speed: "60",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "0.5",
      ground: "2",
      flying: "1",
      psychic: "2",
      bug: "0.5",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "111",
    name: "Rhyhorn",
    img: "http://img.pokemondb.net/artwork/rhyhorn.jpg",
    type: ["Ground", "Rock"],
    misc: { classification: "spikes pokemon" },
    stats: {
      hp: "80",
      attack: "85",
      defense: "95",
      spattack: "30",
      spdefense: "30",
      speed: "25",
    },
    damages: {
      normal: "0.5",
      fire: "0.5",
      water: "4",
      electric: "0",
      grass: "4",
      ice: "2",
      fight: "2",
      poison: "0.25",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "2",
    },
  },
  {
    id: "112",
    name: "Rhydon",
    img: "http://img.pokemondb.net/artwork/rhydon.jpg",
    type: ["Ground", "Rock"],
    misc: { classification: "drill pokemon" },
    stats: {
      hp: "105",
      attack: "130",
      defense: "120",
      spattack: "45",
      spdefense: "45",
      speed: "40",
    },
    damages: {
      normal: "0.5",
      fire: "0.5",
      water: "4",
      electric: "0",
      grass: "4",
      ice: "2",
      fight: "2",
      poison: "0.25",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "0.5",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "2",
    },
  },
  {
    id: "113",
    name: "Chansey",
    img: "http://img.pokemondb.net/artwork/chansey.jpg",
    type: ["Normal"],
    misc: { classification: "egg pokemon" },
    stats: {
      hp: "250",
      attack: "5",
      defense: "5",
      spattack: "35",
      spdefense: "105",
      speed: "50",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "114",
    name: "Tangela",
    img: "http://img.pokemondb.net/artwork/tangela.jpg",
    type: ["Grass"],
    misc: { classification: "vine pokemon" },
    stats: {
      hp: "65",
      attack: "55",
      defense: "115",
      spattack: "100",
      spdefense: "40",
      speed: "60",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "0.5",
      electric: "0.5",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "2",
      ground: "0.5",
      flying: "2",
      psychic: "1",
      bug: "2",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "115",
    name: "Kangaskhan",
    img: "http://img.pokemondb.net/artwork/kangaskhan.jpg",
    type: ["Normal"],
    misc: { classification: "parent pokemon" },
    stats: {
      hp: "105",
      attack: "95",
      defense: "80",
      spattack: "40",
      spdefense: "80",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "116",
    name: "Horsea",
    img: "http://img.pokemondb.net/artwork/horsea.jpg",
    type: ["Water"],
    misc: { classification: "dragon pokemon" },
    stats: {
      hp: "30",
      attack: "40",
      defense: "70",
      spattack: "70",
      spdefense: "25",
      speed: "60",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "117",
    name: "Seadra",
    img: "http://img.pokemondb.net/artwork/seadra.jpg",
    type: ["Water"],
    misc: { classification: "dragon pokemon" },
    stats: {
      hp: "55",
      attack: "65",
      defense: "95",
      spattack: "95",
      spdefense: "45",
      speed: "85",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "118",
    name: "Goldeen",
    img: "http://img.pokemondb.net/artwork/goldeen.jpg",
    type: ["Water"],
    misc: { classification: "goldfish pokemon" },
    stats: {
      hp: "45",
      attack: "67",
      defense: "60",
      spattack: "35",
      spdefense: "50",
      speed: "63",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "119",
    name: "Seaking",
    img: "http://img.pokemondb.net/artwork/seaking.jpg",
    type: ["Water"],
    misc: { classification: "goldfish pokemon" },
    stats: {
      hp: "80",
      attack: "92",
      defense: "65",
      spattack: "65",
      spdefense: "80",
      speed: "68",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "120",
    name: "Staryu",
    img: "http://img.pokemondb.net/artwork/staryu.jpg",
    type: ["Water"],
    misc: { classification: "starshape pokemon" },
    stats: {
      hp: "30",
      attack: "45",
      defense: "55",
      spattack: "70",
      spdefense: "55",
      speed: "85",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "121",
    name: "Starmie",
    img: "http://img.pokemondb.net/artwork/starmie.jpg",
    type: ["Water", "Psychic"],
    misc: { classification: "mysterious pokemon" },
    stats: {
      hp: "60",
      attack: "75",
      defense: "85",
      spattack: "100",
      spdefense: "85",
      speed: "115",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "0.5",
    },
  },
  {
    id: "122",
    name: "Mr. Mime",
    img: "https://img.pokemondb.net/artwork/mr-mime.jpg",
    type: ["Psychic"],
    misc: { classification: "barrier pokemon" },
    stats: {
      hp: "40",
      attack: "45",
      defense: "65",
      spattack: "100",
      spdefense: "120",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "123",
    name: "Scyther",
    img: "http://img.pokemondb.net/artwork/scyther.jpg",
    type: ["Bug", "Flying"],
    misc: { classification: "mantis pokemon" },
    stats: {
      hp: "70",
      attack: "110",
      defense: "80",
      spattack: "55",
      spdefense: "80",
      speed: "105",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "2",
      grass: "0.25",
      ice: "2",
      fight: "0.25",
      poison: "1",
      ground: "0",
      flying: "2",
      psychic: "1",
      bug: "0.5",
      rock: "4",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "124",
    name: "Jynx",
    img: "http://img.pokemondb.net/artwork/jynx.jpg",
    type: ["Ice", "Psychic"],
    misc: { classification: "humanshape pokemon" },
    stats: {
      hp: "65",
      attack: "50",
      defense: "35",
      spattack: "115",
      spdefense: "95",
      speed: "95",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "2",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "2",
    },
  },
  {
    id: "125",
    name: "Electabuzz",
    img: "http://img.pokemondb.net/artwork/electabuzz.jpg",
    type: ["Electric"],
    misc: { classification: "electric pokemon" },
    stats: {
      hp: "65",
      attack: "83",
      defense: "57",
      spattack: "95",
      spdefense: "85",
      speed: "105",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "0.5",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "126",
    name: "Magmar",
    img: "http://img.pokemondb.net/artwork/magmar.jpg",
    type: ["Fire"],
    misc: { classification: "spitfire pokemon" },
    stats: {
      hp: "65",
      attack: "95",
      defense: "57",
      spattack: "100",
      spdefense: "85",
      speed: "93",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "1",
      grass: "0.5",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "127",
    name: "Pinsir",
    img: "http://img.pokemondb.net/artwork/pinsir.jpg",
    type: ["Bug"],
    misc: { classification: "stagbeetle pokemon" },
    stats: {
      hp: "65",
      attack: "125",
      defense: "100",
      spattack: "55",
      spdefense: "70",
      speed: "85",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "0.5",
      flying: "2",
      psychic: "1",
      bug: "1",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "128",
    name: "Tauros",
    img: "http://img.pokemondb.net/artwork/tauros.jpg",
    type: ["Normal"],
    misc: { classification: "wild bull pokemon" },
    stats: {
      hp: "75",
      attack: "100",
      defense: "95",
      spattack: "40",
      spdefense: "70",
      speed: "110",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "129",
    name: "Magikarp",
    img: "http://img.pokemondb.net/artwork/magikarp.jpg",
    type: ["Water"],
    misc: { classification: "fish pokemon" },
    stats: {
      hp: "20",
      attack: "10",
      defense: "55",
      spattack: "15",
      spdefense: "20",
      speed: "80",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "130",
    name: "Gyarados",
    img: "http://img.pokemondb.net/artwork/gyarados.jpg",
    type: ["Water", "Flying"],
    misc: { classification: "atrocious pokemon" },
    stats: {
      hp: "95",
      attack: "125",
      defense: "79",
      spattack: "60",
      spdefense: "100",
      speed: "81",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "4",
      grass: "1",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "131",
    name: "Lapras",
    img: "http://img.pokemondb.net/artwork/lapras.jpg",
    type: ["Water", "Ice"],
    misc: { classification: "transport pokemon" },
    stats: {
      hp: "130",
      attack: "85",
      defense: "80",
      spattack: "85",
      spdefense: "95",
      speed: "60",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.25",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "132",
    name: "Ditto",
    img: "http://img.pokemondb.net/artwork/ditto.jpg",
    type: ["Normal"],
    misc: { classification: "transform pokemon" },
    stats: {
      hp: "48",
      attack: "48",
      defense: "48",
      spattack: "48",
      spdefense: "48",
      speed: "48",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "133",
    name: "Eevee",
    img: "http://img.pokemondb.net/artwork/eevee.jpg",
    type: ["Normal"],
    misc: { classification: "evolution pokemon" },
    stats: {
      hp: "55",
      attack: "55",
      defense: "50",
      spattack: "45",
      spdefense: "65",
      speed: "55",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "134",
    name: "Vaporeon",
    img: "http://img.pokemondb.net/artwork/vaporeon.jpg",
    type: ["Water"],
    misc: { classification: "bubble jet pokemon" },
    stats: {
      hp: "130",
      attack: "65",
      defense: "60",
      spattack: "110",
      spdefense: "95",
      speed: "65",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "2",
      grass: "2",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "135",
    name: "Jolteon",
    img: "http://img.pokemondb.net/artwork/jolteon.jpg",
    type: ["Electric"],
    misc: { classification: "lightning pokemon" },
    stats: {
      hp: "65",
      attack: "65",
      defense: "60",
      spattack: "110",
      spdefense: "95",
      speed: "130",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "0.5",
      grass: "1",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "136",
    name: "Flareon",
    img: "http://img.pokemondb.net/artwork/flareon.jpg",
    type: ["Fire"],
    misc: { classification: "flame pokemon" },
    stats: {
      hp: "65",
      attack: "130",
      defense: "60",
      spattack: "95",
      spdefense: "110",
      speed: "65",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "1",
      grass: "0.5",
      ice: "0.5",
      fight: "1",
      poison: "1",
      ground: "2",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "137",
    name: "Porygon",
    img: "http://img.pokemondb.net/artwork/porygon.jpg",
    type: ["Normal"],
    misc: { classification: "virtual pokemon" },
    stats: {
      hp: "65",
      attack: "60",
      defense: "70",
      spattack: "85",
      spdefense: "75",
      speed: "40",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "138",
    name: "Omanyte",
    img: "http://img.pokemondb.net/artwork/omanyte.jpg",
    type: ["Rock", "Water"],
    misc: { classification: "spiral pokemon" },
    stats: {
      hp: "35",
      attack: "40",
      defense: "100",
      spattack: "90",
      spdefense: "55",
      speed: "35",
    },
    damages: {
      normal: "0.5",
      fire: "0.25",
      water: "1",
      electric: "2",
      grass: "4",
      ice: "0.5",
      fight: "2",
      poison: "0.5",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "139",
    name: "Omastar",
    img: "http://img.pokemondb.net/artwork/omastar.jpg",
    type: ["Rock", "Water"],
    misc: { classification: "spiral pokemon" },
    stats: {
      hp: "70",
      attack: "60",
      defense: "125",
      spattack: "115",
      spdefense: "70",
      speed: "55",
    },
    damages: {
      normal: "0.5",
      fire: "0.25",
      water: "1",
      electric: "2",
      grass: "4",
      ice: "0.5",
      fight: "2",
      poison: "0.5",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "140",
    name: "Kabuto",
    img: "http://img.pokemondb.net/artwork/kabuto.jpg",
    type: ["Rock", "Water"],
    misc: { classification: "shellfish pokemon" },
    stats: {
      hp: "30",
      attack: "80",
      defense: "90",
      spattack: "55",
      spdefense: "45",
      speed: "55",
    },
    damages: {
      normal: "0.5",
      fire: "0.25",
      water: "1",
      electric: "2",
      grass: "4",
      ice: "0.5",
      fight: "2",
      poison: "0.5",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "141",
    name: "Kabutops",
    img: "http://img.pokemondb.net/artwork/kabutops.jpg",
    type: ["Rock", "Water"],
    misc: { classification: "shellfish pokemon" },
    stats: {
      hp: "60",
      attack: "115",
      defense: "105",
      spattack: "65",
      spdefense: "70",
      speed: "80",
    },
    damages: {
      normal: "0.5",
      fire: "0.25",
      water: "1",
      electric: "2",
      grass: "4",
      ice: "0.5",
      fight: "2",
      poison: "0.5",
      ground: "2",
      flying: "0.5",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "142",
    name: "Aerodactyl",
    img: "http://img.pokemondb.net/artwork/aerodactyl.jpg",
    type: ["Rock", "Flying"],
    misc: { classification: "fossil pokemon" },
    stats: {
      hp: "80",
      attack: "105",
      defense: "65",
      spattack: "60",
      spdefense: "75",
      speed: "130",
    },
    damages: {
      normal: "0.5",
      fire: "0.5",
      water: "2",
      electric: "2",
      grass: "1",
      ice: "2",
      fight: "1",
      poison: "0.5",
      ground: "0",
      flying: "0.5",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "2",
    },
  },
  {
    id: "143",
    name: "Snorlax",
    img: "http://img.pokemondb.net/artwork/snorlax.jpg",
    type: ["Normal"],
    misc: { classification: "sleeping pokemon" },
    stats: {
      hp: "160",
      attack: "110",
      defense: "65",
      spattack: "65",
      spdefense: "110",
      speed: "30",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "2",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "0",
      dragon: "1",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "144",
    name: "Articuno",
    img: "http://img.pokemondb.net/artwork/articuno.jpg",
    type: ["Ice", "Flying"],
    misc: { classification: "freeze pokemon" },
    stats: {
      hp: "90",
      attack: "85",
      defense: "100",
      spattack: "95",
      spdefense: "125",
      speed: "85",
    },
    damages: {
      normal: "1",
      fire: "2",
      water: "1",
      electric: "2",
      grass: "0.5",
      ice: "1",
      fight: "1",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "4",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "2",
    },
  },
  {
    id: "145",
    name: "Zapdos",
    img: "http://img.pokemondb.net/artwork/zapdos.jpg",
    type: ["Electric", "Flying"],
    misc: { classification: "electric pokemon" },
    stats: {
      hp: "90",
      attack: "90",
      defense: "85",
      spattack: "125",
      spdefense: "90",
      speed: "100",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "0.5",
      ice: "2",
      fight: "0.5",
      poison: "1",
      ground: "0",
      flying: "0.5",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "146",
    name: "Moltres",
    img: "http://img.pokemondb.net/artwork/moltres.jpg",
    type: ["Fire", "Flying"],
    misc: { classification: "flame pokemon" },
    stats: {
      hp: "90",
      attack: "100",
      defense: "90",
      spattack: "125",
      spdefense: "85",
      speed: "90",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "2",
      electric: "2",
      grass: "0.25",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.25",
      rock: "4",
      ghost: "1",
      dragon: "1",
      dark: "1",
      steel: "0.5",
    },
  },
  {
    id: "147",
    name: "Dratini",
    img: "http://img.pokemondb.net/artwork/dratini.jpg",
    type: ["Dragon"],
    misc: { classification: "dragon pokemon" },
    stats: {
      hp: "41",
      attack: "64",
      defense: "45",
      spattack: "50",
      spdefense: "50",
      speed: "50",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "0.5",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "2",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "148",
    name: "Dragonair",
    img: "http://img.pokemondb.net/artwork/dragonair.jpg",
    type: ["Dragon"],
    misc: { classification: "dragon pokemon" },
    stats: {
      hp: "61",
      attack: "84",
      defense: "65",
      spattack: "70",
      spdefense: "70",
      speed: "70",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "0.5",
      grass: "0.5",
      ice: "2",
      fight: "1",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "1",
      bug: "1",
      rock: "1",
      ghost: "1",
      dragon: "2",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "149",
    name: "Dragonite",
    img: "http://img.pokemondb.net/artwork/dragonite.jpg",
    type: ["Dragon", "Flying"],
    misc: { classification: "dragon pokemon" },
    stats: {
      hp: "91",
      attack: "134",
      defense: "95",
      spattack: "100",
      spdefense: "100",
      speed: "80",
    },
    damages: {
      normal: "1",
      fire: "0.5",
      water: "0.5",
      electric: "1",
      grass: "0.25",
      ice: "4",
      fight: "0.5",
      poison: "1",
      ground: "0",
      flying: "1",
      psychic: "1",
      bug: "0.5",
      rock: "2",
      ghost: "1",
      dragon: "2",
      dark: "1",
      steel: "1",
    },
  },
  {
    id: "150",
    name: "Mewtwo",
    img: "http://img.pokemondb.net/artwork/mewtwo.jpg",
    type: ["Psychic"],
    misc: { classification: "genetic pokemon" },
    stats: {
      hp: "106",
      attack: "110",
      defense: "90",
      spattack: "154",
      spdefense: "90",
      speed: "130",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
  {
    id: "151",
    name: "Mew",
    img: "http://img.pokemondb.net/artwork/mew.jpg",
    type: ["Psychic"],
    misc: { classification: "new specie pokemon" },
    stats: {
      hp: "100",
      attack: "100",
      defense: "100",
      spattack: "100",
      spdefense: "100",
      speed: "100",
    },
    damages: {
      normal: "1",
      fire: "1",
      water: "1",
      electric: "1",
      grass: "1",
      ice: "1",
      fight: "0.5",
      poison: "1",
      ground: "1",
      flying: "1",
      psychic: "0.5",
      bug: "2",
      rock: "1",
      ghost: "2",
      dragon: "1",
      dark: "2",
      steel: "1",
    },
  },
];
